### ISSUE TITLE
Unknown inspection PhpUnused

### ISSUE THREAD

**Issue by dimaconway** [kalessil/phpinspectionsea#1413]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 3.0.16 |
| Language level | PHP 7.2                         |

Current behaviour
--
Error message `Unknown inspection: PhpUnused` after upgrading from 3.0.15 to 3.0.16
Code:
```php
 /** @noinspection PhpUnused */
public function addAction() {...}
```

Expected behaviour
--
No error message.

Environment details
---
PhpStorm 2019.2.1
Build #PS-192.6262.66, built on August 22, 2019
Licensed to PhpStorm Evaluator
Expiration date: October 10, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-27-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1962M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.intellij.ideolog, mobi.hsz.idea.gitignore, BashSupport, com.kalessil.phpStorm.phpInspectionsEA, org.psliwa.idea.composer, ru.adelf.idea.dotenv

**Comment by kalessil** [comment]
Fixed!

**Comment by dimaconway** [comment]
@kalessil unfortunately no. Still experiencing this on 3.0.16.1

**Comment by kalessil** [comment]
The fix is not yet released, coming with the next update.

**Comment by mertasan** [comment]
@kalessil 

<img width="515" alt="screenshot 122" src="https://user-images.githubusercontent.com/13007665/115179057-28ef8580-a0db-11eb-96e9-e207a89cc8d9.png">
<img width="547" alt="screenshot 123" src="https://user-images.githubusercontent.com/13007665/115179060-2a20b280-a0db-11eb-99b4-1c4b6a781252.png">
<img width="640" alt="screenshot 124" src="https://user-images.githubusercontent.com/13007665/115179061-2ab94900-a0db-11eb-8666-654aa1549f8f.png">

**Comment by banagale** [comment]
Just seeing this appear in the above build as well.

**Comment by ea-inspections-team** [comment]
Folks, the issue is still there and we are looking into the root cause. Please track progress on https://github.com/kalessil/phpinspectionsea/issues/1723.

**Comment by mertasan** [comment]
@ea-inspections-team Could you please check again? #1723 is not progressing.

![screenshot 52](https://user-images.githubusercontent.com/13007665/124113000-9886d700-da73-11eb-9088-19dd79b2c792.png)

<img width="685" alt="screenshot 49" src="https://user-images.githubusercontent.com/13007665/124113018-9de42180-da73-11eb-9955-0eafe2b35771.png">

<img width="526" alt="screenshot 50" src="https://user-images.githubusercontent.com/13007665/124113019-9fade500-da73-11eb-9550-eeb940887a5b.png">

<img width="639" alt="screenshot 51" src="https://user-images.githubusercontent.com/13007665/124113020-9fade500-da73-11eb-9d91-b5ce49dc533b.png">

**Comment by StyxUA** [comment]
5.0.0.0 and the problem still exists.

**Comment by wayheming** [comment]
Same problem with 5.0.0.0

**Comment by ea-inspections-team** [comment]
Following up on the latest comment: the relevant issue is https://github.com/kalessil/phpinspectionsea/issues/1901 and the fix will be shipped in next release of plugins.
