### ISSUE TITLE
PHP 8 Null assignment can be safely removed

### ISSUE THREAD

**Issue by rlempa** [kalessil/phpinspectionsea#1753]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.6.4 |
| Language level | PHP 8.0 |

@kalessil You asked in this ticket https://github.com/kalessil/phpinspectionsea/issues/1380 to create a new issue.

![image](https://user-images.githubusercontent.com/3853663/127125311-ec139451-826c-42eb-9aae-845c7f80bf9e.png)

Removing that null will cause `PHP Fatal error: Uncaught Error: Typed property Foo::$bar must not be accessed before initialization`.

So this null can't be safely removed.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @rlempa !
Looks like this has been addressed already in #1549.

**Comment by rentalhost** [comment]
@ea-inspections-team not fixed for v4.0.6.5 (U).

![image](https://user-images.githubusercontent.com/421851/144242622-941bf5ee-5f1f-4c5d-8067-b2cd3ac4d9c2.png)
![image](https://user-images.githubusercontent.com/421851/144242655-da0c4cb0-770d-421f-b422-1f2591be52ab.png)

**Comment by ea-inspections-team** [comment]
Thanks for re-checking @rentalhost ! What's your IDE version?

**Comment by rentalhost** [comment]
@ea-inspections-team great!

> PhpStorm 2021.3
> Build #PS-213.5744.279, built on December 2, 2021
> Windows 10 10.0
> 
> Non-Bundled Plugins:
>     mobi.hsz.idea.gitignore (4.3.0)
>     com.intellij.plugins.html.instantEditing (213.5744.122)
>     ru.adelf.idea.dotenv (2021.3.0.213)
>     com.kalessil.phpStorm.phpInspectionsUltimate-mp (2021.3)
>     de.espend.idea.laravel (0.15.4)
>     com.funivan.idea.phpClean (2021.09.26)

I was updated today, but old versions still happens.

**Comment by ea-inspections-team** [comment]
Fixed!

**Comment by rentalhost** [comment]
@ea-inspections-team this will fix cases like that too?

```php
public stdClass|string|null $x = null;
```

**Comment by ea-inspections-team** [comment]
@rentalhost : yes, we push one more commit.
